#!/bin/bash
set -e

versions=('8.0' '8.1' '8.2')

for v in ${versions[@]}; do
  docker build --build-arg PHP_VERSION=${v} -t apokalipscke/php:${v}-composer -t apokalipscke/php:latest-composer composer/
  docker build --build-arg PHP_VERSION=${v} -t apokalipscke/php:${v}-fpm -t apokalipscke/php:latest-fpm -t apokalipscke/php:latest fpm/
done
