#!/bin/bash
set -e

# composer
# php 7.4
docker build -t apokalipscke/php:7.4-composer composer/7.4/
# php 8.0
docker build -t apokalipscke/php:8.0-composer -t apokalipscke/php:latest-composer composer/8.0/

# fpm
# 7.4
docker build -t apokalipscke/php:7.4-fpm fpm/7.4/
# 8.0
docker build -t apokalipscke/php:8.0-fpm -t apokalipscke/php:latest-fpm -t apokalipscke/php:latest fpm/8.0/
