version: 2.1
executors:
    docker-publisher:
        environment:
            IMAGE_NAME: apokalipscke/php
        docker:
            - image: docker:20.10-git
jobs:
    build:
        executor: docker-publisher
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Build Docker image
                  command: |
                      docker build -t apokalipscke/php:7.4-composer composer/7.4/
            - run:
                  name: Archive Docker image
                  command: docker save -o image.tar $IMAGE_NAME
            - persist_to_workspace:
                  root: .
                  paths:
                      - ./image.tar
    publish-latest:
        executor: docker-publisher
        steps:
            - attach_workspace:
                  at: /tmp/workspace
            - setup_remote_docker
            - run:
                  name: Load archived Docker image
                  command: docker load -i /tmp/workspace/image.tar
            - run:
                  name: Publish Docker Image to Docker Hub
                  command: |
                      echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                      docker push --all-tags $IMAGE_NAME
workflows:
    version: 2
    build-master:
        jobs:
            - build:
                  filters:
                      branches:
                          only: master
            - publish-latest:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master